a.exe : main.o sync.o save.o user.o admin.o menu.o createAccount.o
	gcc main.o sync.o save.o user.o admin.o menu.o createAccount.o
main.o : main.c
	gcc -c main.c
sync.o : sync.c
	gcc -c sync.c
save.o : save.c
	gcc -c save.c
user.o : user.c
	gcc -c user.c
admin.o : admin.c
	gcc -c admin.c
menu.o : menu.c
	gcc -c menu.c
# insertAtEnd.o : insertAtEnd.c
# 	gcc -c insertAtEnd.c
createAccount.o : createAccount.c
	gcc -c createAccount.c
	