a.exe : fread_fwrite.o sync.o save.o createNode.o displayNodes.o insertAtEnd.o
	gcc fread_fwrite.o sync.o save.o createNode.o displayNodes.o insertAtEnd.o
fread_fwrite.o : fread_fwrite.c
	gcc -c fread_fwrite.c
sync.o : sync.c
	gcc -c sync.c
save.o : save.c
	gcc -c save.c
createNode.o : createNode.c
	gcc -c createNode.c
displayNodes.o : displayNodes.c
	gcc -c displayNodes.c
insertAtEnd.o : insertAtEnd.c
	gcc -c insertAtEnd.c
	